### ISSUE TITLE
Group H - Add Required Checks for Accounts Repository

### ISSUE THREAD

**Issue by Marcel-TO** [muhlba91/fh-burgenland-bswe-assignment-infrastructure#50]
**Description:**
To enforce the linting and repository policies to validate before allowing to merge, it is important to add them to the infrastructure yml file.

The following Workflows must pass before merging is allowed for the Group H - Account Repository:
- Conform -> to uphold repository and commit standards
- YAMLLint -> to validate setting files and API specifications in `yml` files are do not contain linting errors
- checkstyle for Java -> to uphold linting standards inside the Java code project

**Comment by muhlba91** [comment]
please try to keep issues in your private repositories and create only the PR here.
in the PR description, just reference the issue in your repository.
